### ISSUE TITLE
panic: port should be within (0, 65535]

### ISSUE THREAD

**Issue by 2019jack** [bnb-chain/greenfield-challenger#84]
### config.json
```
{
          "greenfield_config": {
            "key_type": "local_private_key",
            "aws_region": "",
            "aws_secret_name": "",
            "aws_bls_secret_name": "",
            "private_key": "xxxxx",
            "bls_private_key": "xxxxx",
            "rpc_addrs": [
              "https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org:443"
            ],
            "chain_id_string": "greenfield_5600-1",
            "gas_limit": 100000,
            "fee_amount": "500000000000000",
            "fee_denom": "BNB",
            "no_simulate": true,
            "deduplication_interval": 100
          },
          "log_config": {
            "level": "DEBUG",
            "filename": "",
            "max_file_size_in_mb": 0,
            "max_backups_of_log_files": 0,
            "max_age_to_retain_log_files_in_days": 0,
            "use_console_logger": true,
            "use_file_logger": false,
            "compress": false
          },
          "admin_config": {
            "listen_addr": "0.0.0.0:8080"
          },
          "db_config": {
            "dialect": "mysql",
            "db_path": "tcp(xxxx:3306)/testnet_cedar_greenfield_challenger?charset=utf8&parseTime=True&loc=Local",
            "username": "xxxxx",
            "password": "xxxxx",
            "key_type": "local_private_key",
            "aws_region": "",
            "aws_secret_name": "",
            "max_idle_conns": 20,
            "max_open_conns": 40,
            "debug_mode": true
          },
          "alert_config": {
            "enable_alert": false,
            "enable_heart_beat": false,
            "interval": 300,
            "identity": "",
            "telegram_bot_id": "",
            "telegram_chat_id": "",
            "balance_threshold": "1000000000000000000",
            "sequence_gap_threshold": 10
          }
        }
 ```
 

 error:
 ```
 panic: port should be within (0, 65535]

goroutine 1 [running]:
github.com/bnb-chain/greenfield-challenger/config.(*MetricsConfig).Validate(...)
        /opt/app/config/config.go:134
github.com/bnb-chain/greenfield-challenger/config.(*Config).Validate(0xc000ff7a40)
        /opt/app/config/config.go:142 +0x97
github.com/bnb-chain/greenfield-challenger/config.ParseConfigFromFile({0x7fff00de9dc7?, 0x1b2bd68?})
        /opt/app/config/config.go:167 +0x7b
main.main()
        /opt/app/main.go:81 +0x1d1
```

**Comment by randyahx** [comment]
resolved

**Comment by randyahx** [comment]
The config file was outdated. Please refer to the updated version here.  
https://github.com/bnb-chain/greenfield-challenger/pull/85

**Comment by 2019jack** [comment]
> The config file was outdated. Please refer to the updated version here. #85

to fixed! thanks
