### ISSUE TITLE
mysql 127.0.0.1:3306 connection refused

### ISSUE THREAD

**Issue by 2019jack** [bnb-chain/greenfield-challenger#86]
#### System information

Challenger version: v0.0.6-hf.1
OS & Version: Ubuntu 22.04.1 LTS
Commit hash :  ac1358da14e4b8cadee4af4c07d6ddfc35eb1908

#### running mysql 
``` 
mysql -u root -h 127.0.0.1 -p
CREATE DATAB
ASE challenger;
CREATE SCHEMA IF NOT EXISTS `challenger` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
mysql> show create database challenger;
+------------+--------------------------------------------------------------------------------------------------------------------------------------+
| Database   | Create Database
               |
+------------+--------------------------------------------------------------------------------------------------------------------------------------+
| challenger | CREATE DATABASE `challenger` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */ |
+------------+--------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### db config
db part:
```
"db_config": {
    "dialect": "mysql",
    "db_path": "tcp(127.0.0.1:3306)/challenger?charset=utf8&parseTime=True&loc=Local",
    "username": "root",
    "password": "xxxxxxxxxxxxxxxxxx",
    "key_type": "local_private_key",
    "aws_region": "",
    "aws_secret_name": "",
    "max_idle_conns": 20,
    "max_open_conns": 40,
    "debug_mode": true
  },
  ```

#### logs
```
2023/09/26 05:53:50 /opt/app/app/app.go:45
[error] failed to initialize database, got error dial tcp 127.0.0.1:3306: connect: connection refused
panic: open db error, err=dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
github.com/bnb-chain/greenfield-challenger/app.NewApp(0xc001042a80)
        /opt/app/app/app.go:51 +0xb14
main.main()
        /opt/app/main.go:91 +0x24f
```

### test mysql connection Locally
![mysql-gnfd](https://github.com/bnb-chain/greenfield-challenger/assets/49616005/a806cf3d-8374-416d-8728-06429d3f79a0)

**Comment by 0xLyon** [comment]
Hi there, can you please advise what command you are using to start the challenger?

**Comment by 2019jack** [comment]
> Hi there, can you please advise what command you are using to start the challenger?

command:
```
cd /data/greenfield-challenger/config
docker run -it -v $(pwd)/config.json:/app/config/config.json -e CONFIG_TYPE="local" -e CONFIG_FILE_PATH=/app/config/config.json -d ghcr.io/bnb-chain/greenfield-challenger
```

**Comment by randyahx** [comment]
There might be an issue with ur config file. Could you check if the relevant config settings are correct?

**Comment by 2019jack** [comment]
> There might be an issue with ur config file. Could you check if the relevant config settings are correct?

### config.json
```
{
  "greenfield_config": {
    "key_type": "local_private_key",
    "aws_region": "",
    "aws_secret_name": "",
    "aws_bls_secret_name": "",
    "private_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "bls_private_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "rpc_addrs": [
      "https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org"
    ],
    "chain_id_string": "greenfield_9000-121",
    "gas_limit": 1000,
    "fee_amount": "5000000000000",
    "fee_denom": "BNB"
  },
  "metrics_config": {
    "port": 8080
  },
  "log_config": {
    "level": "DEBUG",
    "filename": "log.txt",
    "max_file_size_in_mb": 0,
    "max_backups_of_log_files": 0,
    "max_age_to_retain_log_files_in_days": 0,
    "use_console_logger": true,
    "use_file_logger": false,
    "compress": false
  },
  "db_config": {
    "dialect": "mysql",
    "db_path": "tcp(127.0.0.1:3306)/challenger?charset=utf8&parseTime=True&loc=Local",
    "username": "root",
    "password": "xxxxxxxxxxxxxxxxxx",
    "key_type": "local_private_key",
    "aws_region": "",
    "aws_secret_name": "",
    "max_idle_conns": 20,
    "max_open_conns": 40,
    "debug_mode": true
  },
  "alert_config": {
    "interval": 300,
    "identity": "",
    "telegram_bot_id": "",
    "telegram_chat_id": ""
  }
}
```

@randyahx

**Comment by 2019jack** [comment]
resolved
